[issue]
# Last updated August 2nd, 2024
user = "Kicksecure"
repo = "security-misc"
rev = "de6f3ea74a5a1408e4351c955ecb7010825364c5"
file = "usr/lib/issue.d/20_security-misc.issue"
sha256 = "00ilswn1661h8rwfrq4w3j945nr7dqd1g519d3ckfkm0dr49f26b"

[gitconfig]
# Last updated August 2nd, 2024
user = "Kicksecure"
repo = "security-misc"
rev = "de6f3ea74a5a1408e4351c955ecb7010825364c5"
file = "etc/gitconfig"
sha256 = "1p3adrbmv7fvy84v3i3m3xrzbc2zdrxzn6prac8f6418vwrdmyp7"

[bluetooth]
# Last updated August 2nd, 2024
user = "Kicksecure"
repo = "security-misc"
rev = "de6f3ea74a5a1408e4351c955ecb7010825364c5"
file = "etc/bluetooth/30_security-misc.conf"
sha256 = "0xyvvgmm0dhf0dfhfj4hdbyf2ma30bpd1m5zx6xnjdfvy2fr44na"

[module-blacklist]
# Last updated August 2nd, 2024
user = "Kicksecure"
repo = "security-misc"
rev = "de6f3ea74a5a1408e4351c955ecb7010825364c5"
file = "etc/modprobe.d/30_security-misc_disable.conf"
sha256 = "1mab9cnnwpc4a0x1f5n45yn4yhhdy1affdmmimmslg8rcw65ajh2"

